name: Dastardly Scan

on:
  push:
    branches:
      - main

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dastardly Scan
        uses: PortSwigger/dastardly-action@v1
        with:
          target-url: https://betadev.mycybercns.com
          output-filename: dastardly-report.xml
