name: Dastardly Scan

on:
  push:
    branches:
      - master

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dastardly Scan
        uses: PortSwigger/dastardly-github-action@v1.0.0
        with:
          target-url: http://testhtml5.vulnweb.com/
          output-filename: /app/dastardly-report.xml

      - name: Publish Test Report
        if: always()                                   
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'     
