name: Dastardly Scan

on:
  push:
    branches:
      - master

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dastardly Scan
        continue-on-error: true
        uses: PortSwigger/dastardly-github-action@v1.0.0
        with:
          target-url: http://betadev.mycybercns.com/
          output-filename: dastardly-report.xml
          
      - name: Commit and Push Report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dastardly-report.xml
          git commit -m "Add Dastardly Report"
          git push origin master
